# src/hs_reference.py — official HS-2 chapter names (WCO standard; stable)
HS2_NAMES = {
    "01":"Live animals","02":"Meat","03":"Fish & seafood","04":"Dairy, eggs, honey",
    "05":"Animal products, nes","06":"Live trees & plants","07":"Edible vegetables",
    "08":"Edible fruit & nuts","09":"Coffee, tea & spices","10":"Cereals",
    "11":"Milling products","12":"Oil seeds","13":"Gums & resins","14":"Vegetable plaiting materials",
    "15":"Animal/vegetable fats & oils","16":"Meat/fish preparations","17":"Sugars & confectionery",
    "18":"Cocoa","19":"Cereal/pastry preparations","20":"Vegetable/fruit preparations",
    "21":"Misc edible preparations","22":"Beverages & spirits","23":"Food industry residues; fodder",
    "24":"Tobacco","25":"Salt, stone, cement","26":"Ores, slag & ash","27":"Mineral fuels & oils",
    "28":"Inorganic chemicals","29":"Organic chemicals","30":"Pharmaceuticals","31":"Fertilisers",
    "32":"Tanning/dyeing; paints","33":"Essential oils; perfumery & cosmetics","34":"Soaps & waxes",
    "35":"Albuminoids; glues; enzymes","36":"Explosives; matches","37":"Photographic goods",
    "38":"Misc chemical products","39":"Plastics","40":"Rubber","41":"Raw hides & leather",
    "42":"Leather articles","43":"Furskins","44":"Wood & articles","45":"Cork","46":"Straw/plaiting articles",
    "47":"Wood pulp","48":"Paper & paperboard","49":"Printed books & newspapers","50":"Silk",
    "51":"Wool","52":"Cotton","53":"Other vegetable fibres","54":"Man-made filaments",
    "55":"Man-made staple fibres","56":"Wadding, felt, rope","57":"Carpets","58":"Special woven fabrics",
    "59":"Coated textile fabrics","60":"Knitted/crocheted fabrics","61":"Apparel, knitted",
    "62":"Apparel, not knitted","63":"Other textile articles","64":"Footwear","65":"Headgear",
    "66":"Umbrellas","67":"Feathers; artificial flowers","68":"Stone/cement articles","69":"Ceramics",
    "70":"Glass & glassware","71":"Pearls, gems & precious metals","72":"Iron & steel",
    "73":"Iron/steel articles","74":"Copper","75":"Nickel","76":"Aluminium","78":"Lead","79":"Zinc",
    "80":"Tin","81":"Other base metals","82":"Tools & cutlery","83":"Misc base metal articles",
    "84":"Machinery & mechanical appliances","85":"Electrical machinery & electronics",
    "86":"Railway stock","87":"Vehicles & parts","88":"Aircraft & spacecraft","89":"Ships & boats",
    "90":"Optical, medical & precision instruments","91":"Clocks & watches","92":"Musical instruments",
    "93":"Arms & ammunition","94":"Furniture, bedding, lamps","95":"Toys, games & sports",
    "96":"Misc manufactured articles","97":"Works of art & antiques",
    "98":"Special/personal effects","99":"Special transactions, nes",
}